### ISSUE TITLE
Better debug formatting

### ISSUE THREAD

**Issue by SpontanCombust** [Lukas3674/rust-bitmask-enum#11]
Hello,

I would like to propose a config option that would improve the readability of bitmask variables printed using the debug formatting {:?}.
At the moment only the default derived implementation is available, which in the output looks like this: `Bitmask { bits: 1 }`.
Without looking at enum's declaration it is impossible to decipher, which value this corresponds to.

My proposition is a `debug_as_vec` config option. Adding it to enum's declaration would cause a custom Debug trait implementation to be created for the type. Said implementation would print the bitmask as a vec of all matching values that exist in the enum. Example:
```rs
#[bitmask]
#[bitmask_config(debug_as_vec)]
pub enum BitmaskDebugAsVec {
    Flag1,
    Flag2,
    Flag12 = Self::Flag1.or(Self::Flag2).bits,
    Flag3,
}

assert_eq!(format!("{:?}", BitmaskDebugAsVec::none()), "[]");
assert_eq!(format!("{:?}", BitmaskDebugAsVec::Flag1), "[Flag1]");
assert_eq!(format!("{:?}", BitmaskDebugAsVec::Flag2), "[Flag2]");
assert_eq!(format!("{:?}", BitmaskDebugAsVec::Flag12), "[Flag1, Flag2, Flag12]");
assert_eq!(format!("{:?}", BitmaskDebugAsVec::Flag3), "[Flag3]");
assert_eq!(format!("{:?}", BitmaskDebugAsVec::full()), "[Flag1, Flag2, Flag12, Flag3]");
```
Not adding the option would mean the default debug formatting, as it has always been.

I have already created a working implementation of this feature on my fork. If you like the idea I will make a PR.

**Comment by SpontanCombust** [comment]
Alternatively, we can add a simple `no_debug` config that would only prevent the Debug trait to be automatically derived. Then the user can implement it himself.

**Comment by Lukas3674** [comment]
Hey,
I actually really like this idea, and it is a perfect use for a config option.

I already looked at your implementation on your fork, and it looks good, so I don't mind if you create a pr that I can merge.
It is missing the README, but I can do that when changing the version.

The only thing I am not 100% certain of is the name of the config option, but truth be told, I am not sure about the ones I can think of either.

Some of my options include:
- `vec_debug`
- `list_debug`
- `advanced_debug`

You see, my main problem seems to be with the word `as`, because it is, in my opinion, unnecessary.

Any thoughts?

**Comment by SpontanCombust** [comment]
I'm totally fine with a different name. I wasn't even sure about mine in the first place. Out of your suggestions, I think I would go with `vec_debug`.
I will change the name, add an entry for it to the README and make a PR.

**Comment by Lukas3674** [comment]
What do you think about instead of just the vec like `[Flag, ...]` we do it more in line with the Debug trait and include the name of the bitmask like `BitmaskVecDebug [Flag, ...]` or even `BitmaskVecDebug { flags: [Flag, ...] }`?

**Comment by SpontanCombust** [comment]
This or make the values inside a vec be full names, like `[BitmaskVecDebug::Flag1, BitmaskVecDebug::Flag2, ...]`.
This way you also get the name of the enum, but retain the formatting akin to vec.

**Comment by Lukas3674** [comment]
I think that I might prefer `BitmaskVecDebug[Flag, ...]`, because it is more in line with the Debug trait but does not add to much bloat with braces and the identifier of the enum before every flag.

**Comment by SpontanCombust** [comment]
All right, I'll go with the `BitmaskVecDebug[Flag, ...]` form.
I didn't like the `BitmaskVecDebug { flags: [Flag, ...] }`, because it somewhat implies that this way there is a `flags` field in the type, which could be misleading.

**Comment by Lukas3674** [comment]
Perfect, thank you for the contribution.
I will merge now but wait with publishing until tomorrow or Sunday, so if you have any changes or suggestions, they can be included.

**Comment by SpontanCombust** [comment]
Ok, I'll change the printing format to the one we've discussed just now then.

**Comment by SpontanCombust** [comment]
All done.

**Comment by SpontanCombust** [comment]
Just as I was going to move on I tried adding both config options to enum's declaration and realised the output is invalid, haha. I'll make a fix right away.

**Comment by Lukas3674** [comment]
Interesting, good catch, can you add a test for that?

**Comment by Lukas3674** [comment]
Ohh, i think I misunderstood, thought it was the config parsing, maybe no test needed!

**Comment by SpontanCombust** [comment]
No no, the test is needed, I am adding it. The funny thing about the mistake in parser is that it takes just one character to be changed to fix it, lol.

**Comment by SpontanCombust** [comment]
The bug was that when `inverted_flags` was also configured, regular values would be printed instead of the inverted ones.
```rust
#[bitmask(u8)]
#[bitmask_config(vec_debug, inverted_flags)]
pub enum BitmaskVecDebug {
    Flag1,
    Flag2
}

println!("{:?}", BitmaskVecDebug::full()); // BitmaskVecDebug[Flag1, Flag1, Flag2, Flag2];
```
