### ISSUE TITLE
Implement inverted flags

### ISSUE THREAD

**Issue by Toromyx** [Lukas3674/rust-bitmask-enum#6]
I came across a use case which was made more ergonomic by having constants of inverted flags: I wanted to match against the opposite of specific flags.

Here is an illustration:
```rust
#[bitmask]
enum Bitmask {
    Flag1,
    Flag2,
}

fn main() {
    /* ... */
    match bitmask {
        Bitmask::NotFlag1 => { /* do something if every flag but 1 is given */ },
        Bitmask::NotFlag2 => { /* do something if every flag but 2 is given */ },
        _ => { /* ... */ }
    }
    /* ... */
}
```

**Comment by Toromyx** [comment]
I implemented this feature in a fork, please take a look: <https://github.com/Lukas3674/rust-bitmask-enum/compare/main...Toromyx:rust-bitmask-enum:feature/%236>

**Comment by Lukas3674** [comment]
Interesting Idea, but I don't like automatically adding enum variants / flags, that the user did not add themselves.
But I would not mind having it either as a feature, or an option on the macro invocation, maybe something like this:
```rust
#[bitmask(usize, inverted_flags)]
enum Bitmask {
    Flag1,
    Flag2,
}
```
Or maybe like this, make it possible to add more config options:
```rust
#[bitmask(usize, config = [inverted_flags])]
enum Bitmask {
    Flag1,
    Flag2,
}
```
What do you think.

Other than that, your code looks good.

**Comment by Toromyx** [comment]
Thanks for the feedback!

I implemented inverted flags as in your first suggestion because it was easier to implement the parsing logic this way. I also upgraded to syn version 2 for the same reason.

I'm also not sure about the naming. I started with `NotX`, but in my opinion that doesn't imply *only* not x and all of the rest. So I renamed the constants to `XInverted`. Do you have a preference?

**Comment by Lukas3674** [comment]
I actually prefer this one, but I can do the parsing once I have the time for it.

```rust
#[bitmask(usize, config = [inverted_flags])]
enum Bitmask {
    Flag1,
    Flag2,
}
```

For the naming, I don't really mind either one so your choice, but I would use `Inverted` or `Not` as a prefix, meaning `InvertedX`.
Edit: Actually I don't know what way would be the best, as a prefix or a suffix.

It will take a couple of days for me to look over your code, no time right now, but if you want you can create a new branch and do a pr.

**Comment by Toromyx** [comment]
Alright, I implemented the other syntax. It wasn't as hard as I thought.
PR: <https://github.com/Lukas3674/rust-bitmask-enum/pull/7>

This new feature probably needs documentation as well?

**Comment by Lukas3674** [comment]
I made a code review, after we merge I will look into adding some way of testing bad macro inputs and add documentation.
Ty for the implementation.

**Comment by Lukas3674** [comment]
Kind of refactored a lot, you can take a look if you want to.
Instead of `#[bitmask(config = [inverted_flags])]` I added the ability to add custom bitmask config options via the `#[bitmask_config(...)]` macro, makes parsing a lot easier.
What do you think?
Will be publishing it in a couple of days if nothing comes up.

**Comment by Toromyx** [comment]
Looks good to me, I learned a lot. I see you also allowed explicit discriminants together with implicit discriminants.

From a library user standpoint I liked having a single attribute, but that's just personal preference.

**Comment by Lukas3674** [comment]
I get the one macro argument, it is the only reason why I am still thinking about it.
The reason it came up is the `#[should_panic]` below the `#[test]` macro. Might look at other big crates to get some inspiration.
Thank you for your contribution, and glad you learnt something.
